### PR TITLE
Updated getting started tutorial to use Chris walkthrough

### PR DESCRIPTION
**Pull request by dob**
This new document that @chrishobcroft wrote would replace [the existing getting started page](http://livepeer.readthedocs.io/en/latest/getting_started.html). The existing page is a little out of date with some details so could use an update. On the other hand, this is a pretty massive walkthrough with very minute details such as how to use the social sites to get test ETH. 

Do we think it's too intense for the starting point of our documentation?

Originally it was proposed as an independent walkthrough of using OBS to broadcast on Livepeer, but it contained so much overlapping content with "Getting Started" and "Broadcasting" that it really doesn't have a place if it doesn't serve as one of those two pages.

### CODE REVIEW

**Comment by chrishobcroft** [comment]
Personally, I don't think it's the right thing for a general "getting started", which I feel we should continue to focus on being a "Getting started [as a software developer]" which probably ought to be something written by @jozanza.

When creating the doc, I was considering this link from the homepage as being the call-to-action that my document would help with:

image

**Comment by dob** [comment]
Ok, I kind of agree that it didn't feel quite right for the developer getting started docs page. But at the same time, it is way more detailed and correct than what is there, so it is appropriate as a getting started as a broadcaster page.

Essentially...it doesn't fit into the current doc hierarchy and may be better as a forum or wiki post that yes, can be linked from that page on the web site. What do you think about it living in the wiki instead so that it can be kept up to date easily and edited by your or anyone without going through the PR process?

**Comment by dob** [comment]
@chrishobcroft The steps to add it there would be to visit this page: https://github.com/livepeer/wiki/wiki/_new

And then just paste the edited Markdown content from here: https://raw.githubusercontent.com/livepeer/docs/d9fd2fe6689554e90ee8b8448eca9205d91d38bc/docs/source/getting_started.md

Into that page.

**Comment by chrishobcroft** [comment]
Done:

https://github.com/livepeer/wiki/wiki/How-to:-set-up-a-broadcasting-node-using-Livepeer-and-OBS

**Comment by dob** [comment]
Excellent. Added to the wiki side bar as well. I'm going to close this PR, but it should still be a goal to update our Getting Started and Broadcaster dev docs to be more accurate than they currently are.

**Pull request closed without merging**
