### PR TITLE
fix: fix broken Studio documentation links

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request fixes several broken studio documentation links.

### CODE REVIEW

**Comment by rickstaa** [comment]
@rafal, there's one broken link to a change you made that I couldn't find the correct link for:

[Broken Link](https://github.com/livepeer/docs/blob/cbe65c9e853eaecec5cbf8e94eb2921fd37b90a4/orchestrators/guides/install-go-livepeer.mdx?plain=1#L130)

If you can point me to the correct page, I can update this pull request to fix the last broken link. 👍🏻

**Review by leszko — APPROVED** [review]

**Comment by rickstaa** [comment]
@leszko, thanks for reviewing this pull request. Do you know what this link should point to?

https://github.com/livepeer/docs/blob/cbe65c9e853eaecec5cbf8e94eb2921fd37b90a4/orchestrators/guides/install-go-livepeer.mdx?plain=1#L130

Once we have this fixed, all broken links will be resolved. If you're not sure, I'm happy to merge the pull request anyway.

**Comment by leszko** [comment]
> @leszko, thanks for reviewing this pull request. Do you know what this link should point to?
> 
> https://github.com/livepeer/docs/blob/cbe65c9e853eaecec5cbf8e94eb2921fd37b90a4/orchestrators/guides/install-go-livepeer.mdx?plain=1#L130
> 
> Once we have this fixed, all broken links will be resolved. If you're not sure, I'm happy to merge the pull request anyway.

Maybe this one? https://docs.livepeer.org/orchestrators/guides/install-go-livepeer

**Comment by rickstaa** [comment]
> > @leszko, thanks for reviewing this pull request. Do you know what this link should point to?
> > https://github.com/livepeer/docs/blob/cbe65c9e853eaecec5cbf8e94eb2921fd37b90a4/orchestrators/guides/install-go-livepeer.mdx?plain=1#L130
> > 
> > Once we have this fixed, all broken links will be resolved. If you're not sure, I'm happy to merge the pull request anyway.
> 
> Maybe this one? https://docs.livepeer.org/orchestrators/guides/install-go-livepeer

I think it was meant to link to the CLI flags. I fixed it and merged the pull request 👍🏻.

**Pull request merged**
