### PR TITLE
docs: added yield calculation and updated "how to guides" to "reference"

### PR DESCRIPTION
**Pull request by 0xcadams**
Added rendering KaTeX math equations according to https://docusaurus.io/docs/markdown-features/math-equations

### CODE REVIEW

**Comment by 0xcadams** [comment]
The CI is failing due to running on 14.x Node version, can we bump Vercel to use 16?
Screen Shot 2022-06-13 at 12 51 22 PM

**Review by adamsoffer — CHANGES_REQUESTED** [review]
Let's keep the briding and l2 migration guides underneath guides and the yield calculation reference doc under reference.

**Comment by adamsoffer** [comment]
> The CI is failing due to running on 14.x Node version, can we bump Vercel to use 16? Screen Shot 2022-06-13 at 12 51 22 PM

Bumped to 16

**Comment by 0xcadams** [comment]
Screen Shot 2022-06-15 at 8 33 28 PM

Done!

**Review by adamsoffer — APPROVED** [review]
Looks good. Can we just replace instances of "ROI" in the document with "yield"?

**Comment by hthillman** [comment]
> Looks good. Can we just replace instances of "ROI" in the document with "yield"?

This! Including in the LaTex equations

**Pull request merged**
