### PR TITLE
docs/install: Add recommended installation step using the install.sh script

### PR DESCRIPTION
**Pull request by hjpotter92**
followup from livepeer/go-livepeer#2282

### CODE REVIEW

**Review by hthillman — COMMENTED** [review]
Overall this looks good to me, is this a *new* installation step or one that we just haven't documented?

**Comment by hjpotter92** [comment]
> Overall this looks good to me, is this a _new_ installation step or one that we just haven't documented?

the gpg verification/generation would be available after livepeer/go-livepeer#2282 gets merged. the script itself still exists, just undocumented.

**Comment by hthillman** [comment]
@hjpotter92 is this good to go? looks like the underlying PR is merged

**Comment by hjpotter92** [comment]
> @hjpotter92 is this good to go? looks like the underlying PR is merged

Yes! I was hoping to have it merged after a new release was created for go-livepeer.

**Review by thomshutt — APPROVED** [review]

**Pull request merged**
